/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites.

Warmth checklist:
	Base: 0
	Covers mouth: +1
	Covers eyes: +1

	Materials
	Thin: -1
	Normal: 0
	Thick: +1

	Max warmth: 3
*/
function initFace() {
	setup.clothes.face = [
		{
			index: 0,
			name: "ничего",
			name_cap: "Ничего",
			variable: "naked",
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "ничего",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		},
		{
			index: 1,
			name: "очки",
			name_cap: "Очки",
			variable: "glasses",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "light blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "silver", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "Это облегчает учебу, но к вам могут придраться в школе.",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "glasses.png",
			accIcon: 0,
		},
		{
			index: 2,
			name: "крутые тёмные очки",
			name_cap: "Крутые тёмные очки",
			variable: "coolshades",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Ускоряет повышение статуса в школе.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "cool_shades.png",
			accIcon: 0,
		},
		{
			index: 3,
			name: "хирургическая маска",
			name_cap: "Хирургическая маска",
			variable: "surgicalmask",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["mask", "covered"],
			gender: "n",
			warmth: 1,
			cost: 2000,
			description: "Скрывает вашу личность.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "surgical_mask.png",
			accIcon: 0,
		},
		{
			index: 4,
			name: "кляп",
			name_cap: "Кляп",
			variable: "gag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "Держи свой рот на замке.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		},
		{
			index: 5,
			name: "повязка на глаза",
			name_cap: "Повязка на глаза",
			variable: "blindfold",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "blindfold"],
			gender: "n",
			warmth: 1,
			cost: 2000,
			description: "Держит тебя в неведении.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		},
		{
			index: 6,
			name: "кляп во рту и повязка на глазах",
			name_cap: "Кляп во рту и повязка на глазах",
			variable: "gagblindfold",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1000,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag", "blindfold"],
			gender: "n",
			warmth: 1,
			cost: 3000,
			description: "Держи рот на замке, а глаза закрытыми.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		},
		{
			index: 7,
			name: "маска мошенника",
			name_cap: "Маска мошенника",
			variable: "skulmask",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["mask", "stealthy"],
			gender: "n",
			warmth: 1,
			cost: 23000,
			description: "Для тех, кто замышляет что-то нехорошее.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "skulduggery_mask.png",
			accIcon: 0,
		},
		{
			index: 8,
			name: "очки в низкой оправе",
			name_cap: "Очки в низкой оправе",
			variable: "lowframe",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "Это облегчает учебу, но к вам могут придраться в школе.",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "low_frame_glasses.png",
			accIcon: 0,
		},
		{
			index: 9,
			name: "очки в форме полумесяца",
			name_cap: "Очки в форме полумесяца",
			variable: "halfmoon",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "Это облегчает учебу, но к вам могут придраться в школе.",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "half_moon_glasses.png",
			accIcon: 0,
		},
		{
			index: 10,
			name: "очки в глубокой оправе",
			name_cap: "Очки в глубокой оправе",
			variable: "deepframe",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "Это облегчает учебу, но к вам могут придраться в школе.",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "deep_frame_glasses.png",
			accIcon: 0,
		},
		{
			index: 11,
			name: "квадратные тёмные очки",
			name_cap: "Квадратные тёмные очки",
			variable: "square",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Ускоряет повышение статуса в школе.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "square_shades.png",
			accIcon: 0,
		},
		{
			index: 12,
			name: "круглые тёмные очки",
			name_cap: "Круглые тёмные очки",
			variable: "round",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Ускоряет повышение статуса в школе.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "round_shades.png",
			accIcon: 0,
		},
		{
			index: 13,
			name: "защитные тёмные очки",
			name_cap: "Защитные тёмные очки",
			variable: "shield",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Ускоряет повышение статуса в школе.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "shield_shades.png",
			accIcon: 0,
		},
		{
			index: 14,
			name: "тёмные очки кошачий глаз",
			name_cap: "тёмные очки кошачий глаз",
			variable: "cateye",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Ускоряет повышение статуса в школе.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "cat_eye_shades.png",
			accIcon: 0,
		},
		{
			index: 15,
			name: "очки пилота",
			name_cap: "Очки пилота",
			variable: "aviator",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["grey", "steel", "blue steel", "bronze", "gold", "silver", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Ускоряет повышение статуса в школе.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["original", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "aviators.png",
			accIcon: 0,
		},
		{
			index: 16,
			name: "очки настоящего панка",
			name_cap: "Очки настоящего панка",
			variable: "punk",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 3500,
			description: "Ускоряет повышение статуса в школе.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "punk_shades.png",
			accIcon: 0,
		},
		{
			index: 17,
			name: "намордник",
			name_cap: "Намордник",
			variable: "muzzle",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["gag"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "Держи свой опасный рот на замке.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "",
			accIcon: 0,
		},
		{
			index: 18,
			name: "бинты живой мумии",
			name_cap: "Бинты живой мумии",
			variable: "mummy",
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 1,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "white",
			type: ["costume"],
			gender: "n",
			warmth: 1,
			cost: 500,
			description: "Такое ощущение, что он сделан из туалетной бумаги.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "mummy_facewrap.png",
			accIcon: 0,
		},
		{
			index: 19,
			name: "защитные очки для плавания",
			name_cap: "Защитные очки для плавания",
			variable: "swimgoggles",
			integrity: 70,
			integrity_max: 70,
			fabric_strength: 25,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["swim", "diving"],
			gender: "n",
			warmth: 1,
			cost: 1500,
			description: "Для того, чтобы сохранить ясность вашего зрения под водой.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "swimming_goggles.png",
			accIcon: 0,
		},
		{
			index: 20,
			name: "вуаль танцовщицы",
			name_cap: "Вуаль танцовщицы",
			variable: "belly",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["dance"],
			gender: "n",
			warmth: 0,
			cost: 8000,
			description: "Экзотическая и манящая.",
			shop: ["forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "belly_dancers_veil.png",
			accIcon: "belly_dancers_veil_acc.png",
		},
		{
			index: 21,
			name: "намордник",
			name_cap: "Намордник",
			variable: "muzzlefetish",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["grey", "black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["gag", "fetish", "covered"],
			gender: "n",
			warmth: 0,
			cost: 12000,
			description: "Держи свой опасный рот на замке.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "muzzle.png",
			accIcon: 0,
		},
		{
			index: 22,
			name: "кляп",
			name_cap: "Кляп",
			variable: "gagfetish",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 8000,
			description: "Держи свой рот на замке.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "gag.png",
			accIcon: 0,
		},
		{
			index: 23,
			name: "кусательный кляп",
			name_cap: "Кусательный кляп",
			variable: "bitgag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "Держи свой рот на замке.",
			shop: [""],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "bit_gag.png",
			accIcon: 0,
		},
		{
			index: 24,
			name: "волчий намордник",
			name_cap: "Волчий намордник",
			variable: "wolfmuzzle",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 1,
			cost: 8000,
			description: "Держи свой рот на замке.",
			shop: [],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "wolf_muzzle.png",
			accIcon: 0,
		},
		{
			index: 25,
			name: "кошачий намордник",
			name_cap: "Кошачий намордник",
			variable: "kittymuzzle",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 1,
			cost: 8000,
			description: "Держи свой рот на замке.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "kitty_muzzle.png",
			accIcon: 0,
		},
		{
			index: 26,
			name: "тканный кляп",
			name_cap: "Тканный кляп",
			variable: "clothgag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 1,
			cost: 500,
			description: "Держи свой рот на замке.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "cloth_gag.png",
			accIcon: 0,
		},
		{
			index: 27,
			name: "кляп из трусиков",
			name_cap: "Кляп из трусиков",
			variable: "pantygag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 500,
			description: "Держи свой рот на замке.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "panty_gag.png",
			accIcon: 0,
		},
		{
			index: 28,
			name: "клейкий кляп",
			name_cap: "Клейкий кляп",
			variable: "tapegag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 500,
			description: "Держи свой рот на замке.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "tape_gag.png",
			accIcon: 0,
		},
		{
			index: 29,
			name: "клап-пенис",
			name_cap: "Клап-пенис",
			variable: "penisgag",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 500,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["fetish", "gag"],
			gender: "n",
			warmth: 0,
			cost: 4500,
			description: "Держит ваш рот наполненным.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			location: 0,
			iconFile: "penis_gag.png",
			accIcon: 0,
		},
		{
			index: 30,
			name: "маска скелета",
			name_cap: "Маска скелета",
			variable: "skele",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "mask"],
			gender: "n",
			warmth: 1,
			cost: 2500,
			description: "На тот случай, если тебе будет что выбрать.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "skeleton_mask.png",
			accIcon: 0,
		},
		{
			index: 31,
			name: "эзотерические зрелища",
			name_cap: "Эзотерические зрелища",
			variable: "esoteric",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["glasses", "esoteric"],
			gender: "n",
			warmth: 0,
			cost: 50000,
			description: "Очки кальянного мастера.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "glasses.png",
			accIcon: 0,
		},
		{
			index: 32,
			name: "противогаз",
			name_cap: "Противогаз",
			variable: "gasmask",
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 25,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "brown", "tan", "olive", "sand", "grey", "white", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["mask", "covered", "costume"],
			gender: "n",
			warmth: 3,
			cost: 20000,
			description: "Скрывает вашу личность, но может вызвать странные взгляды.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			location: 0,
			iconFile: "gas_mask.png",
			accIcon: "gas_mask_acc.png",
		},
		{
			index: 33,
			name: "повязка на глазу",
			name_cap: "Повязка на глазу",
			variable: "eyepatch",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "an",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 0,
			cost: 1000,
			description: "Для плавания в открытом море.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "eyepatch.png",
			accIcon: 0,
		},
		{
			index: 34,
			name: "медицинская повязка на глазу",
			name_cap: "Медицинская повязка на глазу",
			variable: "medical eyepatch",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "an",
			plural: 1,
			colour: 0,
			colour_options: ["black", "white", "grey", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 0,
			cost: 1000,
			description: "Почувствуй себя канеки.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "medical_eyepatch.png",
			accIcon: 0,
		},
		{
			index: 35,
			name: "Собачий намордник",
			name_cap: "Собачий намордник",
			variable: "doggymuzzle",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["gag", "fetish", "covered"],
			gender: "n",
			warmth: 1,
			cost: 16000,
			description: "Держи свой опасный рот на замке.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "doggymuzzle.png",
			accIcon: 0,
		},

		{
			index: 36,
			name: "бамбук",
			name_cap: "Бамбук",
			variable: "bamboomuzzle",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["gag", "fetish", "covered"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "Держи свой опасный рот на замке.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "bamboomuzzle.png",
			accIcon: 0,
		},
		{
			index: 37,
			name: "монокль",
			name_cap: "Монокль",
			variable: "monocle",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "grey", "steel", "blue steel", "bronze", "gold", "silver"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["glasses", "formal"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "Это облегчает учебу, но к вам могут придраться в школе.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "monocle.png",
			accIcon: "monocle_acc.png",
		},
		{
			index: 38,
			name: "маска островитянина",
			name_cap: "Маска островитянина",
			variable: "islandermask",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["mask", "covered", "costume"],
			colour_combat: 0,
			gender: "n",
			warmth: 2,
			cost: 5000,
			description: "Носят островитяне.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "islander_mask.png",
			accIcon: 0,
		},
		{
			index: 39,
			name: "очки для чтения",
			name_cap: "Очки для чтения",
			variable: "reading",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "light blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "silver", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["glasses"],
			gender: "n",
			warmth: 0,
			cost: 5000,
			description: "Это облегчает учебу, но к вам могут придраться в школе.",
			shop: ["clothing", "school"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "reading_glasses.png",
			accIcon: 0,
		},
		{
			index: 40,
			name: "бандана",
			name_cap: "Бандана",
			variable: "bandanna",
			integrity: 20,
			integrity_max: 20,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 1,
			colour: 0,
			colour_options: ["black", "light blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "pale white", "yellow", "silver", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["mask", "covered"],
			gender: "n",
			warmth: 1,
			cost: 500,
			description: "Скрывает вашу личность.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			location: 0,
			iconFile: "bandanna.png",
			accIcon: 0,
		},
		{
			index: 41,
			name: "солнцезащитные очки сердечки",
			name_cap: "Солнцезащитные очки сердечки",
			variable: "heartsunglasses",
			integrity: 30,
			integrity_max: 30,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "neon blue", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["cool"],
			gender: "n",
			warmth: 0,
			cost: 7000,
			description: "Ускоряет повышение статуса в школе.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [
				"light pink",
				"lilac",
				"olive",
				"gold",
				"black",
				"blue",
				"brown",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"neon blue",
				"custom",
			],
			accessory_colour_sidebar: 1,
			altposition: "none",
			altdisabled: [],
			cursed: 0,
			location: 0,
			iconFile: "heart_sunglasses.png",
			accIcon: "heart_sunglasses_acc.png",
		},
	];

	/*
		Clothes that modders add go into this array, this should be empty in the base game at all times.
		These items should have a `modder` variable with a the modders name in a short string
	*/
	setup.moddedClothes.face = [];

	setup.moddedClothes.face.forEach((x, i) => (x.index = setup.clothes.face.length + i));
	setup.clothes.face.push(...setup.moddedClothes.face);
}
window.initFace = initFace;
