/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites. */
function initFeet() {
	setup.clothes.feet = [
		{
			index: 0,
			name: "ничего",
			name_cap: "Ничего",
			variable: "naked",
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "Ничего",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		},
		{
			index: 1,
			name: "школьная обувь",
			name_cap: "Школьная обувь",
			variable: "schoolshoes",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["school"],
			gender: "n",
			warmth: 10,
			cost: 2500,
			description: "Умная и подходящая для школы, но не является обязательной.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "school_shoes.png",
			accIcon: 0,
		},

		{
			index: 2,
			name: "туфли для смокинга",
			name_cap: "Туфли для смокинга",
			variable: "tuxedoshoes",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["formal"],
			gender: "m",
			femininity: -100,
			warmth: 15,
			cost: 10000,
			description: "Умные и утонченные.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "tuxedo_shoes.png",
			accIcon: 0,
		},

		{
			index: 3,
			name: "наручники на лодыжках",
			name_cap: "Наручники на лодыжках",
			variable: "anklecuffs",
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["fetish", "shackle"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "Потребуется специальный инструмент для разблокировки.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			notuck: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		},

		{
			index: 4,
			name: "сандалии",
			name_cap: "Сандалии",
			variable: "sandals",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 0,
			cost: 2000,
			description: "В них будет прохладно летом.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_combat: "brown",
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "sandals.png",
			accIcon: 0,
		},

		{
			index: 5,
			name: "парадные босоножки",
			name_cap: "Парадные босоножки",
			variable: "dresssandals",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 10000,
			description: "Модные и утонченные.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "dress_sandals.png",
			accIcon: 0,
		},

		{
			index: 6,
			name: "кроссовки",
			name_cap: "Кроссовки",
			variable: "trainers",
			integrity: 250,
			integrity_max: 250,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["athletic"],
			gender: "n",
			warmth: 10,
			cost: 3000,
			description: "Непринужденные и практичные.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "trainers.png",
			accIcon: "trainers_acc.png",
		},

		{
			index: 7,
			name: "ведьмины туфли",
			name_cap: "Ведьмины туфли",
			variable: "witch",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume"],
			gender: "f",
			femininity: 200,
			warmth: 20,
			cost: 4000,
			description: "Милые и пугающие.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "witch_shoes.png",
			accIcon: "witch_shoes_acc.png",
		},

		{
			index: 8,
			name: "резиновые сапоги",
			name_cap: "Резиновые сапоги",
			variable: "wellies",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "rugged"],
			gender: "n",
			warmth: 50,
			cost: 5000,
			description: "Водонепроницаемые.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "wellies.png",
			accIcon: 0,
		},

		{
			index: 9,
			name: "каблуки на платформе",
			name_cap: "Каблуки на платформе",
			variable: "platformheels",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 800,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "custom"],
			colour_sidebar: 1,
			type: ["formal", "serving", "bimbo", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 10,
			cost: 5000,
			description: "Ты чувствуешь себя совсем девчушкой.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "platform_heels.png",
			accIcon: 0,
		},

		{
			index: 10,
			name: "кошачьи каблуки",
			name_cap: "Кошачьи каблуки",
			variable: "kittenheels",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 50,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 10,
			cost: 10000,
			description: "Они зовутся кошачьим каблуком, потому что их длина всего три сантиметра.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "kitten_heels.png",
			accIcon: 0,
		},

		{
			index: 11,
			name: "босоножки на танкетке",
			name_cap: "Босоножки на танкетке",
			variable: "wedgesandals",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 400,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 3500,
			description: "Отлично подходят для пляжа.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_combat: 0,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "wedge_sandals.png",
			accIcon: 0,
		},

		{
			index: 12,
			name: "туфли-лодочки на каблуках",
			name_cap: "Туфли-лодочки на каблуках",
			variable: "courtheels",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal", "serving", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 10,
			cost: 12500,
			description: "Довольно высокий и очень взрослый.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "court_heels.png",
			accIcon: 0,
		},

		{
			index: 13,
			name: "сапоги на высоком каблуке",
			name_cap: "Сапоги на высоком каблуке",
			variable: "bootheels",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 600,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["fetish", "serving", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 20,
			cost: 16000,
			description: "Мощный выбор.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "heeled_boots.png",
			accIcon: 0,
		},

		{
			index: 14,
			name: "каблуки для стриптизерш",
			name_cap: "Каблуки для стриптизерш",
			variable: "stripperheels",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 800,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["dance", "fetish", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 10,
			cost: 25000,
			description: "Безумно высокая и очень распутная.",
			shop: ["adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "stripper_heels.png",
			accIcon: 0,
		},

		{
			index: 15,
			name: "мокасины укус лошади",
			name_cap: "Мокасины укус лошади",
			variable: "horsebitloafers",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 10,
			cost: 20000,
			description: "Пара черных мокасин, набитых лошадиным жиром.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "horsebit_loafers.png",
			accIcon: 0,
		},

		{
			index: 16,
			name: "мокасины из кордовской кожи",
			name_cap: "Мокасины из кордовской кожи",
			variable: "cordovanloafers",
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 10,
			cost: 40000,
			description: "Пара мокасин с оболчкой из кордовской кожи. Дорогие, но очень качественные..",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "cordovan_loafers.png",
			accIcon: 0,
		},

		{
			index: 17,
			name: "тапочки-зайчики",
			name_cap: "Тапочки-зайчики",
			variable: "bunny",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "white",
			type: ["sleep"],
			gender: "f",
			femininity: 200,
			warmth: 40,
			cost: 2000,
			description: "Согревает ваши пальцы ног.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "bunny_slippers.png",
			accIcon: 0,
		},

		{
			index: 18,
			name: "армейские ботинки",
			name_cap: "Армейские ботинки",
			variable: "combat",
			integrity: 500,
			integrity_max: 500,
			fabric_strength: 50,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal", "rugged"],
			gender: "m",
			femininity: -100,
			warmth: 20,
			cost: 20000,
			description: "Изготовлены из прочных, высококачественных материалов.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "combat_boots.png",
			accIcon: 0,
		},

		{
			index: 19,
			name: "походные ботинки",
			name_cap: "Походные ботинки",
			variable: "field",
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 40,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal", "riding"],
			gender: "n",
			femininity: 0,
			warmth: 20,
			cost: 14500,
			description: "Гибкие. Подходят для профессиональной езды верхом.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "field_boots.png",
			accIcon: 0,
		},

		{
			index: 20,
			name: "ботинки для загона",
			name_cap: "Ботинки для загона",
			variable: "paddock",
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 40,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal", "riding"],
			gender: "n",
			femininity: 0,
			warmth: 20,
			cost: 8000,
			description: "Для повседневной езды верхом.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "paddock_boots.png",
			accIcon: 0,
		},

		{
			index: 21,
			name: "рабочие ботинки",
			name_cap: "Рабочие ботинки",
			variable: "work",
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 40,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "brown",
			type: ["normal", "rugged"],
			gender: "n",
			femininity: 0,
			warmth: 20,
			cost: 6000,
			description: "Защищает ваши пальцы ног.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "work_boots.png",
			accIcon: 0,
		},

		{
			index: 22,
			name: "ласты",
			name_cap: "Ласты",
			variable: "flippers",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 60,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["swim", "diving", "unstealthy"],
			gender: "n",
			femininity: 0,
			warmth: 30,
			cost: 2000,
			description: "Позволяет вам нырять быстрее.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "flippers.png",
			accIcon: 0,
		},

		{
			index: 23,
			name: "коньки ",
			name_cap: "Коньки ",
			variable: "iceskates",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 10000,
			description: "Прочные, но в то же время элегантные, как и те, кто ими пользуется.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "ice_skates.png",
			accIcon: 0,
		},

		{
			index: 24,
			name: "длинные сапоги",
			name_cap: "Длинные сапоги",
			variable: "long",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 60,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 40,
			cost: 4500,
			description: "Прикрывает твои колени.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "long_boots.png",
			accIcon: 0,
		},

		{
			index: 25,
			name: "Светящиеся кроссовки",
			name_cap: "Светящиеся кроссовки",
			variable: "lightuptrainers",
			integrity: 250,
			integrity_max: 250,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "unstealthy"],
			gender: "n",
			warmth: 10,
			cost: 4500,
			description: "Для лучшей видимости.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "light-up_trainers.png",
			accIcon: "light-up_trainers_acc.png",
		},

		{
			index: 26,
			name: "цепь с шаром",
			name_cap: "Цепь с шаром",
			variable: "ballchain",
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["fetish", "shackle"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "Для разблокировки потребуется специальный инструмент.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			notuck: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		},

		{
			index: 27,
			name: "ковбойские сапоги",
			name_cap: "ковбойские сапоги",
			variable: "cowboy",
			integrity: 350,
			integrity_max: 350,
			fabric_strength: 40,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "brown",
			type: ["normal", "riding"],
			gender: "m",
			femininity: -200,
			warmth: 30,
			cost: 8500,
			description: "Шпоры как у настоящих ковбоев.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "cowboy_boots.png",
			accIcon: 0,
		},

		{
			index: 28,
			name: "высокие кроссовки",
			name_cap: "Высокие кроссовки",
			variable: "hightops",
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 10,
			cost: 6000,
			description: "Модно и практично.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "trainers.png",
			accIcon: "trainers_acc.png",
		},

		{
			index: 29,
			name: "туфли танцовщицы ",
			name_cap: "Туфли танцовщицы",
			variable: "belly",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "f",
			femininity: 200,
			warmth: 20,
			cost: 4000,
			description: "Забавно звенят, при каждом шаге.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "belly_dancers_shoes.png",
			accIcon: 0,
		},

		{
			index: 30,
			name: "брезентовые мокасины",
			name_cap: "Брезентовые мокасины",
			variable: "canvas loafers",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 10,
			cost: 3500,
			description: "Непринужденный и практичный.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "canvas_loafers.png",
			accIcon: "canvas_loafers_acc.png",
		},
		{
			index: 31,
			name: "сапоги на высоком каблуке до бедер",
			name_cap: "Сапоги на высоком каблуке до бедер",
			variable: "thighhigh_heels",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "tan", "grey", "brown", "blue", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["heels"],
			gender: "f",
			femininity: 200,
			warmth: 40,
			cost: 10000,
			description: "Прикрывает твои колени.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "thighhigh_heels.png",
			accIcon: 0,
		},
		{
			index: 32,
			name: "сапоги с мехом",
			name_cap: "Сапоги с мехом",
			variable: "fur_boots",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 250,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "tan", "grey", "brown", "blue", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["heels"],
			gender: "f",
			femininity: 200,
			warmth: 30,
			cost: 7500,
			description: "Для привлечения внимания в клубах.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["white", "brown", "black", "tan", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "fur_boots.png",
			accIcon: "fur_boots_acc.png",
		},
		{
			index: 33,
			name: "мэри Джейн",
			name_cap: "Мэри Джейн",
			variable: "maryjanes",
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "brown", "tan", "white", "light pink", "light blue", "lilac", "custom"],
			colour_sidebar: 1,
			type: ["school"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 2500,
			description: "Умная и подходящая для школы, но не является обязательной.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["steel", "blue steel", "bronze", "gold", "silver", "black", "white"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "mary_janes.png",
			accIcon: "mary_janes_acc.png",
		},
		{
			index: 34,
			name: "платформа Мэри Джейн",
			name_cap: "Платформа Мэри Джейн",
			variable: "platformmaryjanes",
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "brown", "tan", "white", "light pink", "light blue", "lilac", "custom"],
			colour_sidebar: 1,
			type: ["school"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 4500,
			description: "Подходит для школы, но не является обязательным.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["steel", "blue steel", "bronze", "gold", "silver", "black", "white"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "platform_mary_janes.png",
			accIcon: "platform_mary_janes_acc.png",
		},
	];

	/*
		Clothes that modders add go into this array, this should be empty in the base game at all times.
		These items should have a `modder` variable with a the modders name in a short string
	*/
	setup.moddedClothes.feet = [];

	setup.moddedClothes.feet.forEach((x, i) => (x.index = setup.clothes.feet.length + i));
	setup.clothes.feet.push(...setup.moddedClothes.feet);
}
window.initFeet = initFeet;
