/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites.

Warmth checklist:
	Base: 0
	Covers ½ of head: +1 || Covers full head: +2
	Covers ears: +1

	Materials
	Thin: -1
	Normal: 0
	Thick: +1
	Very thick: +2

	Max warmth: 5
*/
/* head_type should only be added to headwear that doesn't play well with certain hairstyles. Hairstyles whose alt_head_type matches the head_type of the worn head item will use an alternate hairstyle instead. */
function initHead() {
	setup.clothes.head = [
		{
			index: 0,
			name: "naked",
			name_cap: "Ничего",
			variable: "naked",
			integrity: 0,
			integrity_max: 0,
			fabric_strength: 0,
			reveal: 1,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "ничего",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		},

		{
			index: 1,
			name: "hairpin",
			name_cap: "Заколка",
			variable: "hairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 500,
			description: "Значительно ускоряет рост волос.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "hairpin.png",
			accIcon: 0,
		},

		{
			index: 2,
			name: "beanie",
			name_cap: "Шапочка",
			variable: "beanie",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["cool"],
			gender: "n",
			warmth: 3,
			cost: 3000,
			description: "Ускоряет повышение статуса в школе.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "beanie.png",
			accIcon: 0,
		},

		{
			index: 3,
			name: "bunny ears",
			name_cap: "Заячьи ушки",
			variable: "bunnyears",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 300,
			word: "a",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "serving"],
			gender: "n",
			warmth: 0,
			cost: 3000,
			description: "Симпатичные ушки на ободке. Деталь наряда кролика.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "bunny_ears.png",
			accIcon: 0,
		},

		{
			index: 4,
			name: "nun's veil",
			name_cap: "Вуаль монахини",
			variable: "nun",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			type: ["holy", "costume"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 2500,
			description: "Защищает ваши волосы от нежелательного воздействия.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			head_type: "veil",
			cursed: 0,
			location: 0,
			iconFile: "nuns_veil.png",
			accIcon: 0,
		},

		{
			index: 5,
			name: "bow",
			name_cap: "Бант",
			variable: "bow",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "lilac", "red", "tangerine", "teal", "pale white", "pale yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 900,
			description: "Милый бант.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "bow.png",
			accIcon: 0,
		},

		{
			index: 6,
			name: "cap",
			name_cap: "шапка",
			variable: "cap",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "shade"],
			gender: "n",
			warmth: 2,
			cost: 2000,
			description: "Защищает тебя от солнца.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "cap.png",
			accIcon: 0,
		},

		{
			index: 7,
			name: "witch hat",
			name_cap: "Шляпа ведьмы",
			variable: "witch",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "shade"],
			gender: "n",
			warmth: 2,
			cost: 3000,
			description: "Пестрая и ароматная.",
			shop: ["forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "witch_hat.png",
			accIcon: "witch_hat_acc.png",
		},

		{
			index: 8,
			name: "christmas hat",
			name_cap: "Рождественская шляпа",
			variable: "christmas",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 4,
			cost: 5000,
			description: "Сейчас самое время.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "christmas_hat.png",
		},

		{
			index: 9,
			name: "chef hat",
			name_cap: "Шляпа шеф-повара",
			variable: "chef",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "serving"],
			gender: "n",
			warmth: 1,
			cost: 5000,
			description: "Защищает волосы от попадания крема.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "chef_hat.png",
		},

		{
			index: 10,
			name: "cowboy hat",
			name_cap: "Ковбойская шляпа",
			variable: "cowboy",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: ["tan", "sand", "brown", "white", "black", "light pink", "light blue", "russet", "grey", "olive", "wine", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume", "shade"],
			gender: "n",
			warmth: 2,
			cost: 8000,
			description: "Защищает вас от солнца.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["tan", "sand", "brown", "white", "black", "light pink", "light blue", "russet", "grey", "olive", "wine", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "cowboy_hat.png",
			accIcon: "cowboy_hat_acc.png",
		},

		{
			index: 11,
			name: "fedora",
			name_cap: "Фетровая шляпа",
			variable: "fedora",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal", "shade"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 5000,
			description: "Мягкая.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "fedora.png",
		},

		{
			index: 12,
			name: "beatnik hat",
			name_cap: "Французский берет",
			variable: "beatnik",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["cool"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 8000,
			description: "Подчиняться - это не в твоем стиле.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "beatnik_hat.png",
		},

		{
			index: 13,
			name: "sou'wester",
			name_cap: "Рыбацкая шляпа",
			variable: "sou",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["rainproof"],
			gender: "n",
			warmth: 2,
			cost: 4000,
			description: "Защищает от дождя.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "souwester.png",
		},

		{
			index: 14,
			name: "flower crown",
			name_cap: "цветочная корона",
			variable: "flower",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			warmth: 0,
			cost: 0,
			description: "Цветочки.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "flower_crown.png",
		},

		{
			index: 15,
			name: "backwards cap",
			name_cap: "Кепка задом наперед",
			variable: "backwardscap",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "shade"],
			gender: "n",
			warmth: 1,
			cost: 2000,
			description: "Защищает вашу шею от солнца.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			head_type: "hat",
			cursed: 0,
			location: 0,
			iconFile: "backwards_cap.png",
			accIcon: 0,
		},

		{
			index: 16,
			name: "alice band",
			name_cap: "Ободок Алисы",
			variable: "alice",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 1100,
			description: "Убирает твои волосы назад.",
			shop: ["clothing", "school", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "alice_band.png",
			accIcon: 0,
		},

		{
			index: 17,
			name: "straw hat",
			name_cap: "Соломенная шляпа",
			variable: "straw",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal", "shade"],
			gender: "n",
			femininity: 0,
			warmth: 1,
			cost: 700,
			description: "Защищает от солнца.",
			shop: ["clothing"],
			shopGroup: "straw",
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "lilac", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "primary",
			head_type: "hat",
			cursed: 0,
			location: 0,
			iconFile: "straw_hat.png",
			accIcon: "straw_hat_acc.png",
		},

		{
			index: 18,
			name: "straw flower hat",
			name_cap: "Соломенная шляпа с цветком",
			variable: "strawflower",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal", "shade"],
			gender: "f",
			femininity: 100,
			warmth: 1,
			cost: 1500,
			description: "Защищает от солнца.",
			shop: ["clothing"],
			shopGroup: "straw",
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "lilac", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "primary",
			head_type: "hat",
			cursed: 0,
			location: 0,
			iconFile: "straw_hat.png",
			accIcon: "straw_hat_acc.png",
		},

		{
			index: 19,
			name: "maid band",
			name_cap: "Ободок горничной",
			variable: "maid",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["maid", "costume", "serving"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 1200,
			description: "Для того, чтобы выглядеть мило во время уборки.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "maid_band.png",
			accIcon: 0,
		},

		{
			index: 20,
			name: "bun covers",
			name_cap: "Крышки для булочек",
			variable: "bun",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 5000,
			description: "Экзотично.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "bun_covers.png",
			accIcon: 0,
		},

		{
			index: 21,
			name: "headband",
			name_cap: "Повязка на голову",
			variable: "band",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["cool"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 1100,
			description: "Убирает волосы с ваших глаз.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "headband.png",
			accIcon: 0,
		},

		{
			index: 22,
			name: "feathered cap",
			name_cap: "Шапочка с пером",
			variable: "feathered",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "shade"],
			gender: "m",
			femininity: -200,
			warmth: 2,
			cost: 2200,
			description: "Для тех случаев, когда тебе есть чем гордиться.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "feathered_cap.png",
			accIcon: 0,
		},

		{
			index: 23,
			name: "large sailor's hat",
			name_cap: "Большая матросская шляпа",
			variable: "sailorbig",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "m",
			femininity: -200,
			warmth: 2,
			cost: 3000,
			description: "Защищает тебя от солнца.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "large_sailors_hat.png",
			accIcon: 0,
		},

		{
			index: 24,
			name: "small sailor's hat",
			name_cap: "Маленькая матросская шапочка",
			variable: "sailorsmall",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "m",
			femininity: -200,
			warmth: 1,
			cost: 2000,
			description: "Защищает тебя от солнца.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "small_sailors_hat.png",
			accIcon: 0,
		},

		{
			index: 25,
			name: "foreign football helmet",
			name_cap: "Иностранный футбольный шлем",
			variable: "football",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 60,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "m",
			femininity: -200,
			warmth: 3,
			cost: 2000,
			description: "Защитный головной убор. Используется в зарубежных видах спорта.",
			shop: ["clothing", "school", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "football_helmet.png",
			accIcon: 0,
		},

		{
			index: 26,
			name: "big bow",
			name_cap: "Большой бант",
			variable: "bigbow",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 300,
			warmth: 0,
			cost: 1400,
			description: "Очень милый.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "big_bow.png",
			accIcon: 0,
		},

		{
			index: 27,
			name: "riding helmet",
			name_cap: "Шлем для верховой езды",
			variable: "riding",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "riding"],
			gender: "n",
			femininity: 0,
			warmth: 3,
			cost: 16000,
			description: "Защитный головной убор.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "riding_helmet.png",
			accIcon: 0,
		},

		{
			index: 28,
			name: "top hat",
			name_cap: "Цилиндр",
			variable: "top",
			integrity: 150,
			integrity_max: 150,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "formal"],
			gender: "m",
			femininity: -200,
			warmth: 2,
			cost: 6000,
			description: "Старомодная утонченность.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "top_hat.png",
			accIcon: 0,
		},

		{
			index: 29,
			name: "umbrella hat",
			name_cap: "Шляпа-зонтик",
			variable: "umbrella",
			integrity: 120,
			integrity_max: 120,
			fabric_strength: 10,
			reveal: 100,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["rainproof", "shade"],
			gender: "n",
			femininity: 0,
			warmth: 1,
			cost: 1500,
			description: "Защищает от дождя, но привлекает к себе внимание.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "umbrella_hat.png",
			accIcon: 0,
		},

		{
			index: 30,
			name: "racing helmet",
			name_cap: "Гоночный шлем",
			variable: "racing",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "riding"],
			gender: "n",
			femininity: 0,
			warmth: 3,
			cost: 15000,
			description: "Для серьезной езды верхом.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "racing_helmet.png",
			accIcon: 0,
		},

		{
			index: 31,
			name: "feathered hair clip",
			name_cap: "Заколка для волос с перьями",
			variable: "featheredhairclip",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "eerie"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 1500,
			description: "Сделано из настоящих перьев.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "feathered_hair_clip.png",
			accIcon: 0,
		},

		{
			index: 32,
			name: "hoodie hood",
			name_cap: "Капющон от худи",
			variable: "hoodie",
			integrity: 180,
			integrity_max: 180,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			one_piece: 1,
			plural: 0,
			hood: 1,
			mask_img: 1,
			colour: 0,
			colour_options: [
				"black",
				"blue steel",
				"grey",
				"white",
				"light pink",
				"light blue",
				"light green",
				"sand",
				"red",
				"pink",
				"purple",
				"tangerine",
				"teal",
				"custom",
			],
			colour_sidebar: 1,
			type: ["normal"],
			set: "hoodie",
			gender: "n",
			warmth: 3,
			cost: 0,
			description: "Переносная социальная защита.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [
				"black",
				"blue steel",
				"grey",
				"white",
				"light pink",
				"light blue",
				"light green",
				"sand",
				"red",
				"pink",
				"purple",
				"tangerine",
				"teal",
				"custom",
			],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_colour: "secondary",
			cursed: 0,
			location: 0,
			outfitSecondary: ["upper", "hoodie"],
			iconFile: 0,
			accIcon: 0,
		},

		{
			index: 33,
			name: "tam o' shanter",
			name_cap: "Тэм о'шантер",
			variable: "tam",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			plural: 0,
			mask_img: 1,
			hood: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 1,
			cost: 4500,
			description: "Для честных мужчин и красивых девушек.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "tam_o_shanter.png",
			accIcon: 0,
		},

		{
			index: 34,
			name: "cat hat",
			name_cap: "Кошачья шляпа",
			variable: "cat",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			hood: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "shade"],
			gender: "n",
			warmth: 2,
			cost: 3000,
			description: "Усы в комплект не входят.",
			shop: ["clothing"],
			shopGroup: "cathat",
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "cat_hat.png",
			accIcon: "cat_hat_acc.png",
		},

		{
			index: 35,
			name: "monster hood",
			name_cap: "Капюшон монстрика",
			variable: "monster",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			one_piece: 1,
			plural: 0,
			hood: 1,
			mask_img: 1,
			colour: 0,
			colour_options: ["apocalypse", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			set: "monsterhoodie",
			gender: "n",
			warmth: 3,
			cost: 0,
			description: "Ррау.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "",
			outfitSecondary: ["upper", "monster hoodie"],
			accIcon: 0,
		},

		{
			index: 36,
			name: "kitty ears",
			name_cap: "Кошачьи ушки",
			variable: "kitty",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "n",
			one_piece: 0,
			plural: 1,
			hood: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "n",
			warmth: 1,
			cost: 1500,
			description: "Милота.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: "combat",
			cursed: 0,
			location: 0,
			iconFile: "kitty_ears.png",
			accIcon: "kitty_ears_acc.png",
		},

		{
			index: 37,
			name: "mini snowman",
			name_cap: "Мини-снеговик",
			variable: "minisnowman",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 5,
			reveal: 1,
			word: "n",
			one_piece: 0,
			plural: 0,
			hood: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 0,
			cost: 2500,
			description: "Удивительно теплый.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "mini_snowman.png",
			accIcon: 0,
		},

		{
			index: 38,
			name: "cow onesie hood",
			name_cap: "Капюшон коровьего комбинезона",
			variable: "cowonesie",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			one_piece: 1,
			plural: 0,
			hood: 1,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			type: ["sleep", "costume"],
			gender: "n",
			warmth: 4,
			cost: 0,
			description: "Уютный.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			cursed: 0,
			location: 0,
			iconFile: "",
			outfitSecondary: ["upper", "cow onesie"],
			accIcon: 0,
		},

		{
			index: 39,
			name: "baseball cap",
			name_cap: "Бейсболка",
			variable: "baseball",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["shade"],
			gender: "n",
			warmth: 1,
			cost: 6000,
			description: "Защищает тебя от солнца.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "baseball_cap.png",
			accIcon: "baseball_cap_acc.png",
		},

		{
			index: 40,
			name: "rose",
			name_cap: "Роза",
			variable: "rose",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["red", "white", "pink", "light pink", "purple", "yellow", "tangerine", "black", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 2000,
			description: "Пахнет свежестью.",
			shop: ["forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "rose.png",
			accIcon: "rose_acc.png",
		},

		{
			index: 41,
			name: "scarecrow hat",
			name_cap: "Шляпа-пугало",
			variable: "scarecrow",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["costume", "shade"],
			gender: "n",
			warmth: 4,
			cost: 1000,
			description: "Носимый пустоголовыми.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "scarecrow_hat.png",
		},

		{
			index: 42,
			name: "fish hairpin",
			name_cap: "Заколка-рыбка",
			variable: "fishhairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 500,
			description: "На ощупь как настоящая кость.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "fish_hairpin.png",
			accIcon: 0,
		},

		{
			index: 43,
			name: "pink nurse hat",
			name_cap: "Розовая шапочка медсестры",
			variable: "pinknurse",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 1200,
			description: "Такие носят медсестры в больнице.",
			shop: ["clothing"],
			shopGroup: "nursehat",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "pink_nurse.png",
			accIcon: 0,
		},

		{
			index: 44,
			name: "plastic nurse hat",
			name_cap: "Пластиковая шапочка медсестры",
			variable: "plasticnurse",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume", "unstealthy"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 1800,
			description: "Легко моется.",
			shop: ["clothing"],
			shopGroup: "nursehat",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "plastic_nurse.png",
			accIcon: 0,
		},

		{
			index: 45,
			name: "transparent nurse hat",
			name_cap: "Прозрачная шапочка медсестры",
			variable: "transparentnurse",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 200,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 2400,
			description: "Легко моется.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "transparent_nurse.png",
			accIcon: 0,
		},

		{
			index: 46,
			name: "bunny headband",
			name_cap: "Зайчий ободок",
			variable: "bunband",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 0,
			cost: 3000,
			description: "Два симпатичных пучка на ленте.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			cursed: 0,
			location: 0,
			iconFile: "bunny_headband.png",
			accIcon: 0,
		},

		{
			index: 47,
			name: "daisy",
			name_cap: "Маргаритка",
			variable: "daisy",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "white",
			type: ["normal"],
			gender: "f",
			warmth: 0,
			cost: 100,
			description: "Одна маргаритка, ее стебель можно продеть в волосы.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "daisy.png",
		},

		{
			index: 48,
			name: "spirit mask",
			name_cap: "Маска духа",
			variable: "spiritmask",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["costume", "eerie"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 6000,
			description: "Не подходит к твоему лицу.",
			shop: ["forest"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "spirit_mask.png",
			accIcon: "spirit_mask_acc.png",
		},

		{
			index: 49,
			name: "raccoon cap",
			name_cap: "Шапка из енота",
			variable: "furcap m",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_combat: 0,
			colour_options: ["black", "brown", "grey", "tan", "sand", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -200,
			warmth: 3,
			cost: 2000,
			description: "Сохраняет вашу голову в тепле.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "brown", "grey", "tan", "sand", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			head_type: "hat",
			cursed: 0,
			location: 0,
			iconFile: "furcapm.png",
			accIcon: "furcapm_acc.png",
		},

		{
			index: 50,
			name: "fur cap",
			name_cap: "Меховая шапка",
			variable: "furcap f",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			colour: 0,
			colour_combat: 0,
			// eslint-disable-next-line prettier/prettier
			colour_options: ["black", "navy blue", "wine", "blue", "brown", "green", "pink", "light pink", "purple", "lilac", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 4,
			cost: 6000,
			description: "Теплая и модная.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			// eslint-disable-next-line prettier/prettier
			accessory_colour_options: ["black", "navy blue", "wine", "blue", "brown", "green", "pink", "light pink", "purple", "lilac", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			head_type: "hat",
			cursed: 0,
			location: 0,
			iconFile: "furcapf.png",
			accIcon: "furcapf_acc.png",
		},

		{
			index: 51,
			name: "conical hat",
			name_cap: "Коническая шляпа",
			variable: "conicalhat",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 30,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["normal", "shade", "rainproof"],
			gender: "n",
			femininity: 0,
			warmth: 1,
			cost: 700,
			description: "Защищает от солнца.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			cursed: 0,
			location: 0,
			iconFile: "conical_hat.png",
		},

		{
			index: 52,
			name: "cat hoodie hood",
			name_cap: "Капюшон кошачьего худи",
			variable: "cat hoodie",
			integrity: 180,
			integrity_max: 180,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			one_piece: 1,
			plural: 0,
			hood: 1,
			mask_img: 1,
			colour: 0,
			// eslint-disable-next-line prettier/prettier
			colour_options: ["black", "blue steel", "grey", "white", "light pink", "light blue", "light green", "sand", "red", "pink", "purple", "tangerine", "teal", "custom"],
			colour_sidebar: "primary",
			type: ["normal"],
			set: "hoodie",
			gender: "n",
			warmth: 3,
			cost: 0,
			description: "Ты знаешь, как делять ня?",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 1,
			cursed: 0,
			location: 0,
			outfitSecondary: ["upper", "cat hoodie"],
			iconFile: 0,
			accIcon: 0,
		},

		{
			index: 53,
			name: "bat beanie",
			name_cap: "Шапочка-летучая мышь",
			variable: "bat beanie",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			type: ["normal"],
			gender: "n",
			warmth: 2,
			cost: 4500,
			description: "Жутковато милая.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 1,
			back_img_acc: 1,
			back_img_acc_colour: "secondary",
			head_type: "veil",
			cursed: 0,
			location: 0,
			iconFile: "bat_beanie.png",
			accIcon: "bat_beanie_acc.png",
		},

		{
			index: 54,
			name: "mini pumpkin",
			name_cap: "Мини-тыква",
			variable: "jackolantern",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 5,
			reveal: 1,
			word: "n",
			one_piece: 0,
			plural: 0,
			hood: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["costume"],
			gender: "n",
			warmth: 0,
			cost: 2500,
			description: "Все очарование джека лантерна, без его непостоянства.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "jackolantern.png",
			accIcon: 0,
		},

		{
			index: 55,
			name: "butterfly hairpin",
			name_cap: "Заколка бабочка",
			variable: "butterflyhairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "lilac", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "f",
			femininity: 100,
			warmth: 0,
			cost: 1500,
			description: "Неотличима от настоящей бабочки.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_combat: "black",
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "butterfly_hairpin.png",
			accIcon: "butterfly_hairpin_acc.png",
		},

		{
			index: 56,
			name: "star hairpin",
			name_cap: "Заколка звёздочка",
			variable: "starhairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_sidebar: 0,
			colour_combat: 0,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 1500,
			description: "Отражает свет, создавая эффект мерцания.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "star_hairpin.png",
			accIcon: "star_hairpin_acc.png",
		},
		{
			index: 57,
			name: "durag",
			name_cap: "Бандана",
			variable: "durag",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 1,
			cost: 500,
			description: "Защищает ваши волосы.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_sidebar: 0,
			mask_img: 1,
			mask_img_ponytail: 0,
			back_img: 1,
			back_img_colour: "primary",
			head_type: "hat",
			cursed: 0,
			location: 0,
			iconFile: "bandanna.png",
			accIcon: 0,
		},
		{
			index: 58,
			name: "kittycat hat",
			name_cap: "Кошачья шапочка",
			variable: "cattail",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 30,
			reveal: 100,
			word: "a",
			plural: 0,
			mask_img: 1,
			mask_img_ponytail: 1,
			hood: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume", "shade"],
			gender: "n",
			warmth: 2,
			cost: 3000,
			description: "Включая усы.",
			shop: ["clothing"],
			shopGroup: "cathat",
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "cat_hat.png",
			accIcon: "cat_hat_acc.png",
		},
		{
			index: 59,
			name: "sexy nun's veil",
			name_cap: "Сексуальная вуаль монахини",
			variable: "nunlewd",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			type: ["holy", "costume", "fetish"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 5000,
			description: "Нельзя сохранить своё лицо чистым, пока ты расстроен и грязен.",
			shop: ["forest"],
			shopGroup: "nunlewd",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			head_type: "veil",
			cursed: 0,
			location: 0,
			iconFile: "sexy_nuns_veil.png",
			accIcon: 0,
		},
		{
			index: 60,
			name: "sexy nun's ornate veil",
			name_cap: "Богато украшенная вуаль сексуальной монахини",
			variable: "nunlewdornate",
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 100,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [],
			type: ["holy", "costume", "fetish"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 5000,
			description: "Нельзя сохранить своё лицо чистым, пока ты расстроен и грязен.",
			shop: ["forest"],
			shopGroup: "nunlewd",
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 1,
			back_img_colour: "primary",
			head_type: "veil",
			cursed: 0,
			location: 0,
			iconFile: "sexy_nuns_veil.png",
			accIcon: 0,
		},
		{
			index: 61,
			name: "newsboy cap",
			name_cap: "Кепка газетчика",
			variable: "newsboy",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 1,
			colour: 0,
			colour_options: [
				"russet",
				"sand",
				"grey",
				"wine",
				"olive",
				"black",
				"blue",
				"brown",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_combat: 0,
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 500,
			description: "Для бедных маленьких уличных мальчишек.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			head_type: "hat",
			cursed: 0,
			location: 0,
			iconFile: "newsboy_cap.png",
		},
		{
			index: 62,
			name: "visor",
			name_cap: "Козырек",
			variable: "visor",
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			mask_img: 0,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_combat: 0,
			colour_sidebar: 1,
			type: ["normal", "shade"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 700,
			description: "Защищает твои глаза от солнца.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "visor.png",
			accIcon: "visor_acc.png",
		},
		{
			index: 63,
			name: "lolita headband",
			name_cap: "Ободок лолиты",
			variable: "lolita",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [
				"light pink",
				"lilac",
				"black",
				"blue",
				"brown",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "f",
			femininity: 200,
			warmth: 0,
			cost: 3100,
			description: "Убирает твои волосы назад.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [
				"light pink",
				"lilac",
				"black",
				"blue",
				"brown",
				"green",
				"pink",
				"purple",
				"red",
				"tangerine",
				"teal",
				"white",
				"yellow",
				"custom",
			],
			accessory_colour_sidebar: 1,
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "lolita_headband.png",
			accIcon: "lolita_headband_acc.png",
		},

		{
			index: 64,
			name: "gold hairpin",
			name_cap: "Gold hairpin",
			variable: "goldhairpin",
			integrity: 50,
			integrity_max: 50,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: 0,
			type: ["holy"],
			gender: "n",
			femininity: 0,
			warmth: 0,
			cost: 500,
			description: "A gift from someone precious.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			back_img: 0,
			cursed: 0,
			location: 0,
			iconFile: "hairpin.png",
			accIcon: 0,
		},
	];

	/*
		Clothes that modders add go into this array, this should be empty in the base game at all times.
		These items should have a `modder` variable with a the modders name in a short string
	*/
	setup.moddedClothes.head = [];

	setup.moddedClothes.head.forEach((x, i) => (x.index = setup.clothes.head.length + i));
	setup.clothes.head.push(...setup.moddedClothes.head);
}
window.initHead = initHead;
