// @ts-check
/* For any item that has a colour_combat tag, set it to 0 if that item ever gets its own combat sprites.

Warmth checklist:
	Base: 0
	Covers ½ feet: 1 || Covers whole feet: 2
	Covers ankles: +1

	Materials:
	Thin: 0
	Normal: +1
	Thick: +2

	Max warmth: 5
*/
function initFeet() {
	/** @type {ClothesItem[]} */
	const clothing = [
		{
			index: 0,
			name: "naked",
			name_cap: "Ничего",
			variable: "naked",
			state: 0,
			state_base: 0,
			integrity: 10,
			integrity_max: 10,
			fabric_strength: 20,
			reveal: 1,
			word: "a",
			plural: 0,
			colour: 0,
			colour_options: [],
			type: ["naked"],
			gender: "n",
			warmth: 0,
			cost: 0,
			description: "Ничего",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
			mainImage: 0,
		},
		{
			index: 1,
			name: "school shoes",
			name_cap: "Школьная обувь",
			variable: "schoolshoes",
			combat: {
				reference: "lightuptrainers",
				accColour: "#0c0c0c",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["school"],
			gender: "n",
			warmth: 2,
			cost: 2500,
			description: "Подходит для школы, но не является обязательной.",
			shop: ["clothing", "school"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "school_shoes.png",
			accIcon: 0,
		},
		{
			index: 2,
			name: "tuxedo shoes",
			name_cap: "Туфли для смокинга",
			variable: "tuxedoshoes",
			combat: {
				reference: "lightuptrainers",
				accColour: "#1d191e",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["formal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 10000,
			description: "Утонченные.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "tuxedo_shoes.png",
			accIcon: 0,
		},
		{
			index: 3,
			name: "ankle cuffs",
			name_cap: "Наручники на лодыжках",
			variable: "anklecuffs",
			combat: {
				accessory: true,
				hasJoinedLimbsAcc: true,
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["fetish", "shackle"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "Потребуется специальный инструмент для снятия.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			notuck: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		},
		{
			index: 4,
			name: "sandals",
			name_cap: "Сандали",
			variable: "sandals",
			combat: {
				reference: "wedgesandals",
				accColour: "#cdb493",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 2000,
			description: "В них будет прохладно летом.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_combat: "brown",
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "sandals.png",
			accIcon: 0,
		},
		{
			index: 5,
			name: "dress sandals",
			name_cap: "Парадные босоножки",
			variable: "dresssandals",
			combat: {
				reference: "wedgesandals",
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 10000,
			description: "Модные и утонченные.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "dress_sandals.png",
			accIcon: 0,
		},
		{
			index: 6,
			name: "trainers",
			name_cap: "Кроссовки",
			variable: "trainers",
			combat: {
				reference: "lightuptrainers",
				hasMainImg: false,
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 250,
			integrity_max: 250,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["athletic"],
			gender: "n",
			warmth: 2,
			cost: 3000,
			description: "Непринужденные и практичные.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "trainers.png",
			accIcon: "trainers_acc.png",
		},
		{
			index: 7,
			name: "witch shoes",
			name_cap: "Ведьмины туфли",
			variable: "witch",
			combat: {
				reference: "courtheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			colour_combat: 0,
			type: ["costume"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 4000,
			description: "Милые и пугающие.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "witch_shoes.png",
			accIcon: "witch_shoes_acc.png",
		},
		{
			index: 8,
			name: "wellies",
			name_cap: "Резиновые сапоги",
			variable: "wellies",
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "rugged"],
			gender: "n",
			warmth: 3,
			cost: 5000,
			description: "Водонепроницаемые.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "wellies.png",
			accIcon: 0,
		},
		{
			index: 9,
			name: "platform heels",
			name_cap: "Каблуки на платформе",
			variable: "platformheels",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 800,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "custom"],
			colour_sidebar: 1,
			type: ["formal", "serving", "bimbo", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 5000,
			description: "Позволяют почувствовать себя женственно.",
			shop: ["adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "platform_heels.png",
			accIcon: 0,
		},
		{
			index: 10,
			name: "kitten heels",
			name_cap: "Кошачьи каблуки",
			variable: "kittenheels",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 50,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 10000,
			description: "Они зовутся кошачьими потому что их длина всего равняется всего лишь трём сантиметрам.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "kitten_heels.png",
			accIcon: 0,
		},
		{
			index: 11,
			name: "wedge sandals",
			name_cap: "Босоножки на танкетке",
			variable: "wedgesandals",
			combat: {
				accColour: "#a18262",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 400,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 3500,
			description: "Отлично подходят для пляжа.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			accessory_colour_combat: 0,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "wedge_sandals.png",
			accIcon: 0,
		},
		{
			index: 12,
			name: "court heels",
			name_cap: "Туфли-лодочки на каблуках",
			variable: "courtheels",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["formal", "serving", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 12500,
			description: "Quite tall and very grown-up.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "court_heels.png",
			accIcon: 0,
		},
		{
			index: 13,
			name: "heeled boots",
			name_cap: "Сапоги на высоком каблуке",
			variable: "bootheels",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 600,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["fetish", "serving", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 3,
			cost: 16000,
			description: "Мощный выбор.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "heeled_boots.png",
			accIcon: 0,
		},
		{
			index: 14,
			name: "stripper heels",
			name_cap: "Каблуки для стриптизерш",
			variable: "stripperheels",
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 800,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["dance", "fetish", "heels"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 25000,
			description: "Crazy tall and very slutty.",
			shop: ["adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "stripper_heels.png",
			accIcon: 0,
		},
		{
			index: 15,
			name: "horsebit loafers",
			name_cap: "Мокасины укус лошади",
			variable: "horsebitloafers",
			combat: {
				reference: "lightuptrainers",
				accColour: "#171717",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 20000,
			description: "Пара черных мокасин, набитых лошадиным жиром.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "horsebit_loafers.png",
			accIcon: 0,
		},
		{
			index: 16,
			name: "cordovan loafers",
			name_cap: "Мокасины из кордовской кожи",
			variable: "cordovanloafers",
			combat: {
				reference: "lightuptrainers",
				accColour: "#40181f",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 40000,
			description: "Пара мокасин с оболчкой из кордовской кожи. Дорогие, но очень качественные..",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "cordovan_loafers.png",
			accIcon: 0,
		},
		{
			index: 17,
			name: "bunny slippers",
			name_cap: "Тапочки-зайчики",
			variable: "bunny",
			combat: {
				reference: "lightuptrainers",
				accColour: "#ffffff",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "white",
			type: ["sleep"],
			gender: "f",
			femininity: 200,
			warmth: 2,
			cost: 2000,
			description: "Согревает ваши пальцы ног.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "bunny_slippers.png",
			accIcon: 0,
		},
		{
			index: 18,
			name: "combat boots",
			name_cap: "Армейские ботинки",
			variable: "combat",
			combat: {
				reference: "bootheels",
				mainColour: "#333333",
			},
			state: 0,
			state_base: 0,
			integrity: 500,
			integrity_max: 500,
			fabric_strength: 50,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal", "rugged"],
			gender: "m",
			femininity: -100,
			warmth: 4,
			cost: 20000,
			description: "Изготовлены из прочных, высококачественных материалов.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "combat_boots.png",
			accIcon: 0,
		},
		{
			index: 19,
			name: "field boots",
			name_cap: "Походные ботинки",
			variable: "field",
			combat: {
				reference: "bootheels",
				mainColour: "#333333",
			},
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 40,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal", "riding"],
			gender: "n",
			femininity: 0,
			warmth: 3,
			cost: 14500,
			description: "Гибкие. Подходят для профессиональной езды верхом.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "field_boots.png",
			accIcon: 0,
		},
		{
			index: 20,
			name: "paddock boots",
			name_cap: "Ботинки для загона",
			variable: "paddock",
			combat: {
				reference: "bootheels",
				mainColour: "#333333",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 40,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["normal", "riding"],
			gender: "n",
			femininity: 0,
			warmth: 2,
			cost: 8000,
			description: "Для повседневной езды верхом.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "paddock_boots.png",
			accIcon: 0,
		},
		{
			index: 21,
			name: "work boots",
			name_cap: "Рабочие ботинки",
			variable: "work",
			combat: {
				reference: "bootheels",
				mainColour: "#b27531",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 40,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "brown",
			type: ["normal", "rugged"],
			gender: "n",
			femininity: 0,
			warmth: 4,
			cost: 6000,
			description: "Защищает ваши пальцы ног.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "work_boots.png",
			accIcon: 0,
		},
		{
			index: 22,
			name: "flippers",
			name_cap: "Ласты",
			variable: "flippers",
			combat: {
				reference: "lightuptrainers",
				hasMainImg: false,
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 60,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["swim", "diving", "unstealthy"],
			gender: "n",
			femininity: 0,
			warmth: 2,
			cost: 2000,
			description: "Позволяет вам нырять быстрее.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "flippers.png",
			accIcon: 0,
		},
		{
			index: 23,
			name: "ice skates",
			name_cap: "Коньки",
			variable: "iceskates",
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 100,
			integrity_max: 100,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 2,
			cost: 10000,
			description: "Прочные, но в то же время элегантные, как и те, кто ими пользуется.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "ice_skates.png",
			accIcon: 0,
		},
		{
			index: 24,
			name: "long boots",
			name_cap: "Длинные сапоги",
			variable: "long",
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 60,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			femininity: 0,
			warmth: 4,
			cost: 4500,
			description: "Прикрывает твои колени.",
			shop: ["clothing", "adult"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "long_boots.png",
			accIcon: 0,
		},
		{
			index: 25,
			name: "light-up trainers",
			name_cap: "Светящиеся кроссовки",
			variable: "lightuptrainers",
			combat: {
				accColour: "#121212",
			},
			state: 0,
			state_base: 0,
			integrity: 250,
			integrity_max: 250,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal", "unstealthy"],
			gender: "n",
			warmth: 1,
			cost: 4500,
			description: "Для лучшей видимости.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "light-up_trainers.png",
			accIcon: "light-up_trainers_acc.png",
		},
		{
			index: 26,
			name: "ball and chain",
			name_cap: "Цепь с шаром",
			variable: "ballchain",
			state: 0,
			state_base: 0,
			integrity: 400,
			integrity_max: 400,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 0,
			colour: 0,
			colour_options: [],
			colour_combat: "black",
			type: ["fetish", "shackle"],
			gender: "n",
			warmth: 0,
			cost: 10000,
			description: "Для разблокировки потребуется специальный инструмент.",
			shop: [],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 1,
			notuck: 1,
			location: 0,
			iconFile: 0,
			accIcon: 0,
		},
		{
			index: 27,
			name: "cowboy boots",
			name_cap: "Ковбойские сапоги",
			variable: "cowboy",
			combat: {
				reference: "bootheels",
				mainColour: "#9a643b",
			},
			state: 0,
			state_base: 0,
			integrity: 350,
			integrity_max: 350,
			fabric_strength: 40,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: [],
			colour_combat: "brown",
			type: ["normal", "riding"],
			gender: "m",
			femininity: -200,
			warmth: 3,
			cost: 8500,
			description: "Шпоры как у настоящих ковбоев.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "cowboy_boots.png",
			accIcon: 0,
		},
		{
			index: 28,
			name: "high top trainers",
			name_cap: "Высокие кроссовки",
			variable: "hightops",
			combat: {
				reference: "lightuptrainers",
				accColour: "primary",
				hasMainImg: false,
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 2,
			cost: 6000,
			description: "Модно и практично.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "trainers.png",
			accIcon: "trainers_acc.png",
		},
		{
			index: 29,
			name: "belly dancer's shoes",
			name_cap: "Туфли танцовщицы",
			variable: "belly",
			combat: {
				reference: "courtheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["costume"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 4000,
			description: "Забавно звенят, при каждом шаге.",
			shop: ["forest"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "belly_dancers_shoes.png",
			accIcon: 0,
		},

		{
			index: 30,
			name: "canvas loafers",
			name_cap: "Брезентовые мокасины",
			variable: "canvas loafers",
			combat: {
				reference: "wedgesandals",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 1,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "m",
			femininity: -100,
			warmth: 2,
			cost: 3500,
			description: "Непринужденный и практичный.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["black", "blue", "brown", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "canvas_loafers.png",
			accIcon: "canvas_loafers_acc.png",
		},
		{
			index: 31,
			name: "thigh-high heeled boots",
			name_cap: "Сапоги на высоком каблуке до бедер",
			variable: "thighhigh_heels",
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 500,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "tan", "grey", "brown", "blue", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["heels"],
			gender: "f",
			femininity: 200,
			warmth: 4,
			cost: 10000,
			description: "Прикрывает твои колени.",
			shop: ["clothing"],
			accessory: 0,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "thighhigh_heels.png",
			accIcon: 0,
		},
		{
			index: 32,
			name: "fur boots",
			name_cap: "Сапоги с мехом",
			variable: "fur_boots",
			combat: {
				reference: "bootheels",
			},
			state: 0,
			state_base: 0,
			integrity: 200,
			integrity_max: 200,
			fabric_strength: 20,
			reveal: 250,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "tan", "grey", "brown", "blue", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["heels"],
			gender: "f",
			femininity: 200,
			warmth: 4,
			cost: 7500,
			description: "Для привлечения внимания в клубах.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["white", "brown", "black", "tan", "custom"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 0,
			location: 0,
			iconFile: "fur_boots.png",
			accIcon: "fur_boots_acc.png",
		},
		{
			index: 33,
			name: "mary janes",
			name_cap: "Туфли мэри Джейн",
			variable: "maryjanes",
			combat: {
				reference: "kittenheels",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "brown", "tan", "white", "light pink", "light blue", "lilac", "custom"],
			colour_sidebar: 1,
			type: ["school"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 2500,
			description: "Подходят для школы, но не являются обязательными.",
			shop: ["clothing"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["steel", "blue steel", "bronze", "gold", "rose gold", "silver", "black", "white"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "mary_janes.png",
			accIcon: "mary_janes_acc.png",
		},
		{
			index: 34,
			name: "platform mary janes",
			name_cap: "Платформа Мэри Джейн",
			variable: "platformmaryjanes",
			combat: {
				reference: "wedgesandals",
				accColour: "primary",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "brown", "tan", "white", "light pink", "light blue", "lilac", "custom"],
			colour_sidebar: 1,
			type: ["school"],
			gender: "f",
			femininity: 200,
			warmth: 1,
			cost: 4500,
			description: "Подходят для школы, но не являются обязательными.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: ["steel", "blue steel", "bronze", "gold", "rose gold", "silver", "black", "white"],
			accessory_colour_sidebar: 1,
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "platform_mary_janes.png",
			accIcon: "platform_mary_janes_acc.png",
		},
		{
			index: 35,
			name: "geta",
			name_cap: "Geta",
			variable: "geta",
			combat: {
				reference: "wedgesandals",
				accColour: "#e49a7d",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "tan", "grey", "brown", "blue", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 4500,
			description: "Exotic.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "geta.png",
			accIcon: "geta_acc.png",
		},
		{
			index: 36,
			name: "zori",
			name_cap: "Zori",
			variable: "zori",
			combat: {
				reference: "wedgesandals",
				accColour: "#e49a7d",
			},
			state: 0,
			state_base: 0,
			integrity: 300,
			integrity_max: 300,
			fabric_strength: 20,
			reveal: 200,
			word: "n",
			plural: 1,
			colour: 0,
			colour_options: ["black", "tan", "grey", "brown", "blue", "green", "pink", "purple", "red", "tangerine", "teal", "white", "yellow", "custom"],
			colour_sidebar: 1,
			type: ["normal"],
			gender: "n",
			warmth: 1,
			cost: 3500,
			description: "Exotic.",
			shop: ["clothing", "adult"],
			accessory: 1,
			accessory_colour: 0,
			accessory_colour_options: [],
			cursed: 0,
			notuck: 1,
			location: 0,
			iconFile: "zori.png",
			accIcon: "zori_acc.png",
		},
	];
	setup.clothes.feet = clothing;

	/*
		Clothes that modders add go into this array, this should be empty in the base game at all times.
		These items should have a `modder` variable with a the modders name in a short string
	*/
	setup.moddedClothes.feet = [];

	setup.moddedClothes.feet.forEach((x, i) => (x.index = setup.clothes.feet.length + i));
	setup.clothes.feet.push(...setup.moddedClothes.feet);
}
window.initFeet = initFeet;
